# Generated by Django 4.1.3 on 2023-02-13 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memopad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
