# Generated by Django 4.1.3 on 2023-02-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memopad', '0002_memo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='text',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
