# Generated by Django 4.1.3 on 2023-02-24 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memopad', '0003_memo_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='tags',
            field=models.ManyToManyField(blank=True, to='memopad.tag'),
        ),
    ]
