# Generated by Django 4.1.3 on 2023-03-15 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='save_book_id',
            new_name='save_memo_id',
        ),
    ]
